export const balls = [
  {
    id: 3,
    code: "qc1",
    name: "街道",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 10,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-jiedao.webp", import.meta.url),
    children: [
      {
        id: 47,
        code: "qc1-1",
        name: "1.为老+银行",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 10,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 313px; margin-bottom: 30px' src=''><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 48,
        code: "qc1-2",
        name: "2.为老+菜场",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 20,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 49,
        code: "qc1-3",
        name: "3.为老+道路",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 30,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 50,
        code: "qc1-4",
        name: "4.为老+餐位",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 40,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 51,
        code: "qc1-5",
        name: "5.为老+绿化",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 50,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 52,
        code: "qc1-6",
        name: "6.为老+研发",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 60,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      }
    ]
  },
  {
    id: 4,
    code: "qc2",
    name: "线上",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 20,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-xianshang.webp", import.meta.url),
    children: [
      {
        id: 53,
        code: "qc2-1",
        name: "1.多元化的线上服务",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 10,
        isDeleted: false,
        parentId: 4,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 54,
        code: "qc2-2",
        name: "2.甘泉养老百事通",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 20,
        isDeleted: false,
        parentId: 4,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      }
    ]
  },
  {
    id: 5,
    code: "qc3",
    name: "家庭",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 30,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-jiating.webp", import.meta.url),
    children: [
      {
        id: 55,
        code: "qc3-1",
        name: "1.室内空间适老化改造",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 10,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 56,
        code: "qc3-2",
        name: "2.老吾老计划(个人、政府)",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 20,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 57,
        code: "qc3-3",
        name: "3.长护险",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 30,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 58,
        code: "qc3-4",
        name: "4.家庭照护床位、家庭病床",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 40,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 59,
        code: "qc3-5",
        name: "5.独居老人安装灶气报警器(政府)",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 50,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      }
    ]
  },
  {
    id: 6,
    code: "qc4",
    name: "楼组",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 40,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-louzu.webp", import.meta.url),
    children: [
      {
        id: 60,
        code: "qc4-1",
        name: "1.楼组硬件环境改善",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 10,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 61,
        code: "qc4-2",
        name: "2.楼组无障碍设施(硬件)",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 20,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 62,
        code: "qc4-3",
        name: "3.楼组加装电梯和适老化设计",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 30,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 63,
        code: "qc4-4",
        name: "4.楼组做网格机制",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 40,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 64,
        code: "qc4-5",
        name: "5.楼组老伙伴计划",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 50,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 65,
        code: "qc4-6",
        name: "6.楼组导向标志等",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 60,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      }
    ]
  },
  {
    id: 7,
    code: "qc5",
    name: "小区",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 50,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-xiaoqu.webp", import.meta.url),
    children: []
  },
  {
    id: 8,
    code: "qc6",
    name: "片区",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 60,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-pianqu.webp", import.meta.url),
    children: []
  },
  {
    id: 3,
    code: "qc1",
    name: "街道",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 10,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-jiedao.webp", import.meta.url),
    children: [
      {
        id: 47,
        code: "qc1-1",
        name: "1.为老+银行",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 10,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 48,
        code: "qc1-2",
        name: "2.为老+菜场",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 20,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 49,
        code: "qc1-3",
        name: "3.为老+道路",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 30,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 50,
        code: "qc1-4",
        name: "4.为老+餐位",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 40,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 51,
        code: "qc1-5",
        name: "5.为老+绿化",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 50,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 52,
        code: "qc1-6",
        name: "6.为老+研发",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 60,
        isDeleted: false,
        parentId: 3,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      }
    ]
  },
  {
    id: 4,
    code: "qc2",
    name: "线上",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 20,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-xianshang.webp", import.meta.url),
    children: [
      {
        id: 53,
        code: "qc2-1",
        name: "1.多元化的线上服务",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 10,
        isDeleted: false,
        parentId: 4,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 54,
        code: "qc2-2",
        name: "2.甘泉养老百事通",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 20,
        isDeleted: false,
        parentId: 4,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      }
    ]
  },
  {
    id: 5,
    code: "qc3",
    name: "家庭",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 30,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-jiating.webp", import.meta.url),
    children: [
      {
        id: 55,
        code: "qc3-1",
        name: "1.室内空间适老化改造",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 10,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 56,
        code: "qc3-2",
        name: "2.老吾老计划(个人、政府)",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 20,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 57,
        code: "qc3-3",
        name: "3.长护险",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 30,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 58,
        code: "qc3-4",
        name: "4.家庭照护床位、家庭病床",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 40,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 59,
        code: "qc3-5",
        name: "5.独居老人安装灶气报警器(政府)",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 50,
        isDeleted: false,
        parentId: 5,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      }
    ]
  },
  {
    id: 6,
    code: "qc4",
    name: "楼组",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 40,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-louzu.webp", import.meta.url),
    children: [
      {
        id: 60,
        code: "qc4-1",
        name: "1.楼组硬件环境改善",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 10,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 61,
        code: "qc4-2",
        name: "2.楼组无障碍设施(硬件)",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 20,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 62,
        code: "qc4-3",
        name: "3.楼组加装电梯和适老化设计",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 30,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 63,
        code: "qc4-4",
        name: "4.楼组做网格机制",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 40,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 64,
        code: "qc4-5",
        name: "5.楼组老伙伴计划",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 50,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      },
      {
        id: 65,
        code: "qc4-6",
        name: "6.楼组导向标志等",
        smallPicture: "",
        bigPicture: "",
        displayOrder: 60,
        isDeleted: false,
        parentId: 6,
        content: "<img style='width: 100%; height: 1.4rem; margin-bottom: 30px' src='/photo@2x (1).webp' /><div style='font-size: 16px; line-height: 26px; color: #fff;'>室内空间适老化改造是指对老年人居住的室内空间进行改造和优化，以提高老年人的生活质量和安全性。适老化改造的目的是为了满足老年人的特殊需求和生活习惯，让他们能够更加舒适、安全地生活在自己的家中。适老化改造的内容包括但不限于以下几个方面：无障碍改造：对室内空间进行无障碍改造，包括安装扶手、斜坡、轮椅通道等以方便老年人的行动。卫生间改造：对卫生间进行改造，安装扶手、坐便器、洗浴设施等，以方便老年人的洗漱和洗浴。厨房改造：对厨房进行改造，安装扶手、低柜台、易于操作的厨具等，以方便老年人的烹饪和饮食。安全改造：对室内空间进行安全改造，安装防滑地面、烟雾报警器、紧急呼叫按钮等以保障老年人的安全。</div>",
        children: []
      }
    ]
  },
  {
    id: 7,
    code: "qc5",
    name: "小区",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 50,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-xiaoqu.webp", import.meta.url),
    children: []
  },
  {
    id: 8,
    code: "qc6",
    name: "片区",
    smallPicture: "",
    bigPicture: "",
    displayOrder: 60,
    isDeleted: false,
    parentId: 1,
    iconUrl: new URL("@/assets/disc-pianqu.webp", import.meta.url),
    children: []
  }
]
